export enum ErrorCode {
  SERVER_ERROR = '서버 오류 입니다. 관리자에게 문의해주세요',
  TIMEOUT_ERROR = '요청이 시간 초과되었습니다.',
  ABORT_REQUEST = '요청이 취소되었습니다.',
  UNKNOWN_ERROR = '알 수 없는 서버 오류가 발생했습니다.',
  EXCEL_UPLOAD_FAILED = '엑셀업로드에 실패하였습니다',
  ACCESS_DENIED = '잘못된 접근입니다',
  INVALID_PATH = '잘못된 경로로 접근하였습니다.',
  INVALID_SESSION = '잘못된 세션 입니다',
  UNKNOWN = '예상치 못한 오류가 발생했습니다.',
  INVALIDATE_PARAMETER = '잘못된 파라메터 입니다.',
  UNAUTHORIZED = 'UNAUTHORIZED',
  EXPIRED_SESSION_TEXT = '세션이 만료되어 로그인 페이지로 이동합니다.',
  ERROR_GET_NEW_TOKEN = '새로운 토큰값을 받아오는데 실패하였습니다.',
  FILE_NOT_FOUND_MESSAGE = '파일이 존재하지 않습니다',
}
