import { Toaster } from "@/components/ui/sonner";
import QueryProvider from "@/shared/providers/query-provider";
import type { Metadata } from "next";
import { Roboto, Sora } from 'next/font/google';
import "./globals.css";

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
});

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${sora.variable} antialiased`}
      >
        <QueryProvider>
            <div className='flex min-h-dvh w-full min-w-[280px] flex-1 flex-row overflow-hidden font-sora'>
                <Toaster
                  richColors
                  // position='top-center'
                  // expand={true}
                  className='pointer-events-auto z-50 touch-manipulation select-text'
                />
                {children}
              </div>
        </QueryProvider>
      </body>
    </html>
  );
}
