import { Toaster } from '@/components/ui/sonner';
import QueryProvider from '@/shared/providers/query-provider';
import type { Metadata } from 'next';
import { Roboto, Sora } from 'next/font/google';
import './globals.css';

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
});

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${roboto.variable} ${sora.variable} flex min-h-dvh w-full min-w-full justify-center bg-gray-50 antialiased`}
      >
        <QueryProvider>
          <div className='font-sora flex min-h-dvh w-full max-w-[1440px]'>
            <Toaster
              richColors
              className='pointer-events-auto z-50 touch-manipulation select-text'
            />
            <div className='flex flex-1'>{children}</div>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
